r.cost: reorder options, the usual order is input-output
The main options input and output are always or almost always in
the order input-output not the other way aroud as it was here.
With output-input order, r.cost travel_time output=travel_cost caused:
ERROR: Option <output> does not accept multiple answers
ERROR: Required parameter <input> not set
Now the help says:
r.cost input=name output=name

Although we don't consider using unnamed parameter or order of parameters
part of API, https://trac.osgeo.org/grass/changeset/72720 which swapped input and output breaks any user
scripts, workflows or documentation which use the first unamed parameter.


git-svn-id: https://svn.osgeo.org/grass/grass/trunk@73144 15284696-431f-4ddb-bdfa-cd5b030d7da7