configure: update PDAL compilation test
WIP

With Fedora 45 the autoconf based PDAL test fails with undeclared definitions, see:

```sh
configure:10554: checking whether to use PDAL
configure:10573: result: yes
configure:10603: g++ -std=gnu++11 -o conftest -g -Wall  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--no-undefined -Wl,-z,now -Wl,--export-dynamic conftest.cpp  -L/usr/lib -lpdalcpp >&5
In file included from /usr/include/pdal/pdal_types.hpp:49,
                 from /usr/include/pdal/pdal_internal.hpp:42,
                 from /usr/include/pdal/SpatialReference.hpp:37,
                 from /usr/include/pdal/PointTable.hpp:41,
                 from conftest.cpp:59:
/usr/include/pdal/util/Utils.hpp:979:31: error: 'std::enable_if_t' has not been declared
  979 |     template<typename T, std::enable_if_t<!std::is_integral<T>::value>* = nullptr>
      |                               ^~~~~~~~~~~
/usr/include/pdal/util/Utils.hpp:979:31: note: 'std::enable_if_t' is only available from C++14 onwards
/usr/include/pdal/util/Utils.hpp:979:42: error: expected '>' before '<' token
  979 |     template<typename T, std::enable_if_t<!std::is_integral<T>::value>* = nullptr>

[...]
```

This PR correctly retrieves the CPP flags and uses them for the configure test.